### ISSUE TITLE
mvn test

### ISSUE THREAD

**Issue by acherm** [Nrkz/PDLProject#16]
> [mathieuacher@localhost PDLProject]$ mvn test
> [INFO] Scanning for projects...
> [WARNING] 
> [WARNING] Some problems were encountered while building the effective model for fr.istic:WikipediaMatrix:jar:1.0-SNAPSHOT
> [WARNING] 'dependencies.dependency.version' for org.jetbrains:annotations:jar is either LATEST or RELEASE (both of them are being deprecated) @ line 41, column 22
> [WARNING] 
> [WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
> [WARNING] 
> [WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
> [WARNING] 
> [INFO] 
> [INFO] ----------------------< fr.istic:WikipediaMatrix >----------------------
> [INFO] Building WikipediaMatrix 1.0-SNAPSHOT
> [INFO] --------------------------------[ jar ]---------------------------------
> [INFO] 
> [INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ WikipediaMatrix ---
> [INFO] Using 'UTF-8' encoding to copy filtered resources.
> [INFO] skip non existing resourceDirectory /home/mathieuacher/Documents/INPROGRESS/PDL2020/PDLProject/src/main/resources
> [INFO] 
> [INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ WikipediaMatrix ---
> [INFO] Nothing to compile - all classes are up to date
> [INFO] 
> [INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ WikipediaMatrix ---
> [INFO] Using 'UTF-8' encoding to copy filtered resources.
> [INFO] skip non existing resourceDirectory /home/mathieuacher/Documents/INPROGRESS/PDL2020/PDLProject/src/test/resources
> [INFO] 
> [INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ WikipediaMatrix ---
> [INFO] Changes detected - recompiling the module!
> [INFO] Compiling 5 source files to /home/mathieuacher/Documents/INPROGRESS/PDL2020/PDLProject/target/test-classes
> [INFO] -------------------------------------------------------------
> [WARNING] COMPILATION WARNING : 
> [INFO] -------------------------------------------------------------
> [WARNING] /home/mathieuacher/Documents/INPROGRESS/PDL2020/PDLProject/src/test/java/pdl/wiki/PageTest.java: /home/mathieuacher/Documents/INPROGRESS/PDL2020/PDLProject/src/test/java/pdl/wiki/PageTest.java uses unchecked or unsafe operations.
> [WARNING] /home/mathieuacher/Documents/INPROGRESS/PDL2020/PDLProject/src/test/java/pdl/wiki/PageTest.java: Recompile with -Xlint:unchecked for details.
> [INFO] 2 warnings 
> [INFO] -------------------------------------------------------------
> [INFO] -------------------------------------------------------------
> [ERROR] COMPILATION ERROR : 
> [INFO] -------------------------------------------------------------
> [ERROR] /home/mathieuacher/Documents/INPROGRESS/PDL2020/PDLProject/src/test/java/pdl/wiki/SavePathTest.java:[8,17] package org.junit does not exist
> [ERROR] /home/mathieuacher/Documents/INPROGRESS/PDL2020/PDLProject/src/test/java/pdl/wiki/SavePathTest.java:[9,17] package org.junit does not exist
> [ERROR] /home/mathieuacher/Documents/INPROGRESS/PDL2020/PDLProject/src/test/java/pdl/wiki/SavePathTest.java:[10,17] package org.junit does not exist
> [ERROR] /home/mathieuacher/Documents/INPROGRESS/PDL2020/PDLProject/src/test/java/pdl/wiki/SavePathTest.java:[23,10] cannot find symbol
>   symbol:   class Before
>   location: class pdl.wiki.SavePathTest
> [ERROR] /home/mathieuacher/Documents/INPROGRESS/PDL2020/PDLProject/src/test/java/pdl/wiki/SavePathTest.java:[33,10] cannot find symbol
>   symbol:   class Test
>   location: class pdl.wiki.SavePathTest
> [ERROR] /home/mathieuacher/Documents/INPROGRESS/PDL2020/PDLProject/src/test/java/pdl/wiki/SavePathTest.java:[45,10] cannot find symbol
>   symbol:   class Test
>   location: class pdl.wiki.SavePathTest
> [ERROR] /home/mathieuacher/Documents/INPROGRESS/PDL2020/PDLProject/src/test/java/pdl/wiki/SavePathTest.java:[57,10] cannot find symbol
>   symbol:   class Test
>   location: class pdl.wiki.SavePathTest
> [ERROR] /home/mathieuacher/Documents/INPROGRESS/PDL2020/PDLProject/src/test/java/pdl/wiki/SavePathTest.java:[69,10] cannot find symbol
>   symbol:   class Test
>   location: class pdl.wiki.SavePathTest
> [ERROR] /home/mathieuacher/Documents/INPROGRESS/PDL2020/PDLProject/src/test/java/pdl/wiki/SavePathTest.java:[81,10] cannot find symbol
>   symbol:   class Test
>   location: class pdl.wiki.SavePathTest
> [ERROR] /home/mathieuacher/Documents/INPROGRESS/PDL2020/PDLProject/src/test/java/pdl/wiki/SavePathTest.java:[93,10] cannot find symbol
>   symbol:   class Test
>   location: class pdl.wiki.SavePathTest
> [ERROR] /home/mathieuacher/Documents/INPROGRESS/PDL2020/PDLProject/src/test/java/pdl/wiki/SavePathTest.java:[105,10] cannot find symbol
>   symbol:   class Test
>   location: class pdl.wiki.SavePathTest
> [ERROR] /home/mathieuacher/Documents/INPROGRESS/PDL2020/PDLProject/src/test/java/pdl/wiki/SavePathTest.java:[119,10] cannot find symbol
>   symbol:   class After
>   location: class pdl.wiki.SavePathTest
> [INFO] 12 errors 
> [INFO] -------------------------------------------------------------
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 0.935 s
> [INFO] Finished at: 2020-01-16T16:45:12+01:00
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile) on project WikipediaMatrix: Compilation failure: Compilation failure: 
> [ERROR] /home/mathieuacher/Documents/INPROGRESS/PDL2020/PDLProject/src/test/java/pdl/wiki/SavePathTest.java:[8,17] package org.junit does not exist
> [ERROR] /home/mathieuacher/Documents/INPROGRESS/PDL2020/PDLProject/src/test/java/pdl/wiki/SavePathTest.java:[9,17] package org.junit does not exist
> [ERROR] /home/mathieuacher/Documents/INPROGRESS/PDL2020/PDLProject/src/test/java/pdl/wiki/SavePathTest.java:[10,17] package org.junit does not exist
> [ERROR] /home/mathieuacher/Documents/INPROGRESS/PDL2020/PDLProject/src/test/java/pdl/wiki/SavePathTest.java:[23,10] cannot find symbol
> [ERROR]   symbol:   class Before
> [ERROR]   location: class pdl.wiki.SavePathTest
> [ERROR] /home/mathieuacher/Documents/INPROGRESS/PDL2020/PDLProject/src/test/java/pdl/wiki/SavePathTest.java:[33,10] cannot find symbol
> [ERROR]   symbol:   class Test
> [ERROR]   location: class pdl.wiki.SavePathTest
> [ERROR] /home/mathieuacher/Documents/INPROGRESS/PDL2020/PDLProject/src/test/java/pdl/wiki/SavePathTest.java:[45,10] cannot find symbol
> [ERROR]   symbol:   class Test
> [ERROR]   location: class pdl.wiki.SavePathTest
> [ERROR] /home/mathieuacher/Documents/INPROGRESS/PDL2020/PDLProject/src/test/java/pdl/wiki/SavePathTest.java:[57,10] cannot find symbol
> [ERROR]   symbol:   class Test
> [ERROR]   location: class pdl.wiki.SavePathTest
> [ERROR] /home/mathieuacher/Documents/INPROGRESS/PDL2020/PDLProject/src/test/java/pdl/wiki/SavePathTest.java:[69,10] cannot find symbol
> [ERROR]   symbol:   class Test
> [ERROR]   location: class pdl.wiki.SavePathTest
> [ERROR] /home/mathieuacher/Documents/INPROGRESS/PDL2020/PDLProject/src/test/java/pdl/wiki/SavePathTest.java:[81,10] cannot find symbol
> [ERROR]   symbol:   class Test
> [ERROR]   location: class pdl.wiki.SavePathTest
> [ERROR] /home/mathieuacher/Documents/INPROGRESS/PDL2020/PDLProject/src/test/java/pdl/wiki/SavePathTest.java:[93,10] cannot find symbol
> [ERROR]   symbol:   class Test
> [ERROR]   location: class pdl.wiki.SavePathTest
> [ERROR] /home/mathieuacher/Documents/INPROGRESS/PDL2020/PDLProject/src/test/java/pdl/wiki/SavePathTest.java:[105,10] cannot find symbol
> [ERROR]   symbol:   class Test
> [ERROR]   location: class pdl.wiki.SavePathTest
> [ERROR] /home/mathieuacher/Documents/INPROGRESS/PDL2020/PDLProject/src/test/java/pdl/wiki/SavePathTest.java:[119,10] cannot find symbol
> [ERROR]   symbol:   class After
> [ERROR]   location: class pdl.wiki.SavePathTest
> [ERROR] -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by BastienAM** [comment]
https://github.com/Nrkz/PDLProject/commit/f01679774077ae4b60f118681a56424588db6c31 Fixed !
